### ISSUE TITLE
Font customisation

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkey-type#111]

**Comment by Le-SirH** [comment]
I think this is a feature where users may choose a font for their test.

**Comment by Miodec** [comment]
Yup, add an option to the setings page aswell as the command line. Probably make a fonts.json file with all the available fonts to choose from.

**Comment by mkviperz** [comment]
I think downloading a bunch of fonts and putting them in the root folder and then implementing them in the fonts.json file would be good. I am currently working on it

**Comment by Miodec** [comment]
You could include webfonts for now, which you dont have to download. Also just to clarify, i think it would be best to only change the font of the test, while keeping everything else in Roboto Mono to keep the aesthetic of the website consistent.

**Comment by Le-SirH** [comment]
Could downloading a lot of fonts slow things down significantly?

**Comment by Miodec** [comment]
Probably. Obviously you dont need to download webfonts, but for any custom ones it would be cool if we could figure out a way to only download the font when the user actually wants to use it

**Comment by Le-SirH** [comment]
Could we store a large number of links to font imports and only import them when the user selects a font?

**Comment by corey-b** [comment]
Using google-fonts to embed some popular fonts that users can change in settings. Also possibly some options to enable font effects like glitch and fire animation.
