### ISSUE TITLE
Fix the title responsiveness to be able to use on resized tabs

### ISSUE THREAD

**Issue by chireia** [Miodec/monkey-type#123]
Normally i like to use something like this:

![image](https://user-images.githubusercontent.com/34220771/83959363-42346e00-a84a-11ea-8c4c-9cf822ebd2ba.png)

To keep practicing even when i'm procrastinating
😄

**Comment by chireia** [comment]
I'm working on it right now, and i didn't found nothing like on the other open issues. What do you guys think?

**Comment by Miodec** [comment]
Yeah, you would need to probably create a burger menu to fit the icons and the test configs. Im not sure about other screens, but i can image it would be a nightmare to make sure that everything is scalable. All though, maybe its possible with just some media queries.

This would also make the website accessible to mobile, and people actually asked for that (for some reason)

**Comment by Miodec** [comment]
Added
