### ISSUE TITLE
Error with ô or î characters

### ISSUE THREAD

**Issue by Ferannor** [Miodec/monkey-type#135]
In French some words has a ^ over a letter. Example: "boîte" or "île".
Each time one of this characters appear, even if I type it correctly, Monkey type find an error on it and sometime on the next character.

**Comment by Miodec** [comment]
Are you using combine keys? Are you pressing `^` and then `i` after? Because this is not supported. Its actually a big issue that I havent figured out yet, you can see my findings in #36

**Comment by Ferannor** [comment]
Yes I'm pressing `^` then `I`. Sorry I didn't saw this issue.

**Comment by Miodec** [comment]
Closing duplicate issue
