### ISSUE TITLE
Please consider adding a nord (dark) theme

### ISSUE THREAD

**Issue by bwoodruff** [Miodec/monkey-type#14]
https://www.nordtheme.com/

**Comment by Miodec** [comment]
![Screenshot 2020-05-15 at 17 24 54](https://user-images.githubusercontent.com/13181393/82073484-39c89780-96d1-11ea-841f-d2680fa9bb30.png)
![Screenshot 2020-05-15 at 17 24 26](https://user-images.githubusercontent.com/13181393/82073488-3b925b00-96d1-11ea-8686-7c88cca46d8e.png)

How do they look, which one would you prefer?

**Comment by Miodec** [comment]
![Screenshot 2020-05-15 at 17 38 04](https://user-images.githubusercontent.com/13181393/82074541-d7709680-96d2-11ea-9abb-87292c7fe28b.png)

Or this one, bit less green and more blue

**Comment by Miodec** [comment]
Added fa08185575bcaddaea7d524453d1dfbf27f738cb

**Comment by bwoodruff** [comment]
Any of those look great. My preference, in order, would be 2, 3, 1. Thanks so much! Great tool.

**Comment by Miodec** [comment]
Yup, thats the one added! Glad you like it
