### ISSUE TITLE
WPM Chart - Responsive Range

### ISSUE THREAD

**Issue by Le-SirH** [Miodec/monkey-type#146]
## Problem
Sometimes, it can be hard to see the differences in the WPM chart after taking a typing test when the WPM range is much larger than the actual WPM range. For example, a user may take a test with a peak speed of 105wpm and a minimum speed of 95wpm but the chart range is 0-110wpm.

![](https://cdn.discordapp.com/attachments/713472607759892571/722558431566758028/unknown.png)

### Possible Solution
The chart range should be dependent on the test results. For example, if the test results range is 90-110wpm, the chart WPM range should be 80-120wpm, leaving a 10wpm gap on the top and bottom of the chart. 

Instead of a fixed value, this could be 10% of the peak speed:

|  | Test Results | Chart Range |
|---|---|---|
| Peak WPM | 110 | **121** |
| Minimum WPM | 90 | **79** |

WPM Gap: **11WPM**, `110 * 0.1`

|  | Test Results | Chart Range |
|---|---|---|
| Peak WPM | 210 | **231** |
| Minimum WPM | 170 | **149** |

WPM Gap: **21WPM**, `210 * 0.1`

### Alternatives
Alternatively, this chart gap of 10% of the peak speed could instead be dependent on the gap between the peak WPM and minimum WPM (210WPM - 170WPM = 40WPM gap):

|  | Test Results | Chart Range |
|---|---|---|
| Peak WPM | 110 | **130** |
| Minimum WPM | 90 | **70** |

WPM Gap: **20WPM**, `110 - 90`

|  | Test Results | Chart Range |
|---|---|---|
| Peak WPM | 210 | **250** |
| Minimum WPM | 170 | **120** |

WPM Gap: **40WPM**, `210 - 170`

**Comment by Miodec** [comment]
My Discord response:

> The issue is that the longer you type, your wpm is averaged over a greater number, so no matter how you set the chat scale, it will always produce a smoother and smoother line towards the end
What needs to be done is to figure out how to get wpm per second, or 5 seconds

> Instead of averaging

> This will produce some meaningful jumps and dips

> Alternatively - wpm per word or per group of words

The problem is that its not easy to properly calculate wpm per second since the user might be in the middle of a word as the seconds 'ticks' and becuase of that that word will not be considered in the previous or next second (since its not complete, it will not count towards wpm, only raw)

The only way of doing it might be wpm per word, and then graphing that

**Comment by Miodec** [comment]
Partially implemented in e132c59d9c4a8ee9c3e345173a10ceca3354056d. Feels like the best idea to have the raw graph be 'momentary' and the actual wpm still be a global average.
