### ISSUE TITLE
Add brackets, number sign, at sign, slash, backslash, ...

### ISSUE THREAD

**Issue by mattiasduerrmeier** [Miodec/monkey-type#149]
I enjoy the punctuation Mode a lot in monkey-type. It improved my typing speed my ability to find certain punctuation marks and characters more easily on the keyboard. 

I suggest adding other punctuation mark and other characters. This would make this Mode a little more difficult and closer to what you would type regularly (For example, when writing a document or programming).
To keep the punctuation Mode as it is, I propose to add a new Mode next to punctuation Mode. For the name, maybe something like **exhaustive Mode** (this is the closest name I could think of to make the name Mode as self explanatory as possible).

#list of characters:
- **[ ]** square brackets
- **{ }** curly brackets
- **( )** round brackets / parentheses
- **@** at sign
- **'** apostrophe (single & double)
- **"** quotes (single & double)
- **`** grave accent (single & double)
- **_** underscore
- **...** ellipsis marks
- **#** number sign / ash
- **/** slash
- **\\** backslash
- **|** vertical bar
- **+** plus sign
- **=** equals sign
- **&** ampersand
- **$** dollar sign

I think that I listed most of them. Feel free to complete the list with other characters, Unicode or punctuation mark that are not in the list.

**Comment by throwawaywords** [comment]
I don't think this'd be useful. Maybe custom text mode might be better and you still can do whatever you want.

**Comment by snth** [comment]
For programmers this would be very useful. I agree with the OP that this should be a new mode rather than modifying the existing punctuation mode.

**Comment by TheChaddestDave** [comment]
I think that only the most common symbols should be used. Maybe brackets, apostrophe, ampersand and quotes, since these are often used in literature.

**Comment by Miodec** [comment]
Added in a form of funbox mode "specials".
