### ISSUE TITLE
Chrome warns user of deceptive site upon registering account

### ISSUE THREAD

**Issue by Jdude311** [Miodec/monkey-type#15]
When making a new account, Chrome warned me of a deceptive site.
Chrome Build: 81.0.4044.138 (Official Build) (64-bit) (cohort: Stable)

**Comment by Miodec** [comment]
I think its the paypal link, will se if 77c3a18e2dd283500cc8025e6d9f2c7af93e0853 will fix it. Could you try and create a new account?
