### ISSUE TITLE
Solarized Light and Dark theme

### ISSUE THREAD

**Issue by jkjrmlg** [Miodec/monkey-type#168]
I've made a couple of themes to contribute to monkey-type. I've always loved the Solarized themes for my IDEs but there isn't one for monkey-type so I decided to make one.

Solarized Dark:
<img width="1280" alt="Screenshot 2020-07-01 at 3 05 12 PM" src="https://user-images.githubusercontent.com/66762550/86214153-5b141300-bbad-11ea-8bb6-5fbae34ae227.png">
<img width="1280" alt="Screenshot 2020-07-01 at 3 05 56 PM" src="https://user-images.githubusercontent.com/66762550/86214171-6109f400-bbad-11ea-8b76-f8ab47198670.png">
Solarized Light:
<img width="1280" alt="Screenshot 2020-07-01 at 3 22 02 PM" src="https://user-images.githubusercontent.com/66762550/86215047-ab3fa500-bbae-11ea-941d-b129b066d252.png">
<img width="1280" alt="Screenshot 2020-07-01 at 3 22 15 PM" src="https://user-images.githubusercontent.com/66762550/86215058-aed32c00-bbae-11ea-9980-ddcf5a79cfba.png">

If you're alright with the themes, do let me know how you'd prefer me to merge the themes.

**Comment by Miodec** [comment]
Yeah, submit a pr.

**Comment by jkjrmlg** [comment]
Done and done
