### ISSUE TITLE
Move Restart test tooltip to below

### ISSUE THREAD

**Issue by huteri** [Miodec/monkey-type#170]
Hi, The tooltip keep blocking me when I type
Suggestion: Move tooltip to below the button 
![Screenshot 2020-07-03 at 10 41 57 AM](https://user-images.githubusercontent.com/4598788/86426434-42753b80-bd1a-11ea-8bc2-df28e7a5b793.png)

**Comment by Miodec** [comment]
8ce94846659938e3685a46821fe82e14431cbc08
