### ISSUE TITLE
Performance issue in Firefox

### ISSUE THREAD

**Issue by gbedardsice** [Miodec/monkey-type#18]
Thanks for the nice work! From [this comment](https://www.reddit.com/r/MechanicalKeyboards/comments/gk9pp8/monkeytypecom_is_now_available_the_new/fqr4z45/):

> I tried it a few times, on Firefox on a MB pro 2016, and it's stuttering / freezing quite a bit for me. I thought it might be because of the smooth cursor, but turning it off didn't help. Switching to Chrome seems to solve the issue, but still might be worth looking into!

![monkey-type](https://user-images.githubusercontent.com/680623/82097946-f02c7c80-96d1-11ea-97ca-1da8fa3f4e76.gif)

**Comment by Miodec** [comment]
Thanks, looking into it soon

**Comment by Miodec** [comment]
This is really annoying, because im not getting that stuttering on a 2014 MB Air.. Do you have the latest Firefox version installed?

**Comment by gbedardsice** [comment]
Hmm, I do have the latest firefox, but after testing a few times, the issue seems intermittent. It might also be related to other processes hogging the cpu on my machine. Feel free to close if you don't think it's worth putting too much time into.

**Comment by Miodec** [comment]
Ill close this for now, see if i get more reports of this happening

**Comment by aviegdown** [comment]
i got an issue today, cpu usage is quite unacceptable, it takes more than 60% cpu usage and stutter a bit

yesterday it just around 20-40% cpu usage and run smoothly

![monkeytype](https://user-images.githubusercontent.com/72583750/106237509-9359fd80-6231-11eb-81a5-2a26d3977d51.png)
