### ISSUE TITLE
Show all words at once 

### ISSUE THREAD

**Issue by winterNebs** [Miodec/monkey-type#180]
I believe one of the recent updates changed the behavior of how word count tests work.

Before the 100 word test would show all 100 words, but now it only shows a small portion.

Would it be possible to get this behavior back as a toggle option?

**Comment by Miodec** [comment]
As mentioned in the release notes, this is to make the words mode more familliar, simmilar to time, to increase performance, limit the number of clutter on the screen and make sure live wpm and timer/progress text is always visible. Plus calculating scrolling is very slow and expensive for some reason.

**Comment by winterNebs** [comment]
So you have no plans to bring the format back even as an option? 

I personally haven't been affected by any performance issues with that, and I like it a lot better than the short format that basically every other game has (10ff, keybr, etc)

**Comment by Miodec** [comment]
Might, some people have also been asking for it

**Comment by Miodec** [comment]
Added in latest update
