### ISSUE TITLE
Change incorrect letter text color on bushido theme

### ISSUE THREAD

**Issue by iitsalex** [Miodec/monkey-type#20]
![image](https://user-images.githubusercontent.com/20635452/82112719-6e097b80-9704-11ea-9ce0-9576a162699f.png)
Bushido theme has a very similar red colored text which makes it hard to differentiate errors correct text when typing.

Love the site by the way!

**Comment by Miodec** [comment]
Fixed 1f0b6af93160cf5d98f661203aab9f1b8f653966
