### ISSUE TITLE
WPM is always equal to raw WPM

### ISSUE THREAD

**Issue by GrayStrider** [Miodec/monkey-type#240]
I've been using this for a while, and my wpm and raw wpm are always the same. Maybe there's some setting I've overlooked?

**Comment by Miodec** [comment]
If you correct all your mistakes / make no mistakes at all raw will be the same as wpm

**Comment by GrayStrider** [comment]
So the raw WPM cannot be higher than WPM? I thought that were these spikes I see on the graph tbh

**Comment by Miodec** [comment]
No, it’s not always the same. Otherwise whats would be the point. Did you figure it out? :)
