### ISSUE TITLE
Temporarily remember the finished test screen for longer tests?

### ISSUE THREAD

**Issue by TheChaddestDave** [Miodec/monkey-type#253]
Remember longer test's finished page, so that if you accidentally go off the page into the stats, or for whatever reason, you don't need to worry about losing the ability to screenshot the graph or see words history.

Good idea or bad idea? I can see myself getting paranoid towards the end of long tests. Not sure about others.

**Comment by Miodec** [comment]
Just take a screenshot at the end of a test. Quick restart is impossible anyway on long tests
