### ISSUE TITLE
can't view account

### ISSUE THREAD

**Issue by staceyfras** [Miodec/monkey-type#312]
After logging into account, clicking on account icon results in an infinite loading screen.

Chrome error:
![image](https://user-images.githubusercontent.com/32045253/90968437-0d2ad580-e4a1-11ea-9557-fa1710f0103c.png)

If anyone can help, thanks. I tried clearing cache, restarting session, and changing my password.

**Comment by Miodec** [comment]
Alright, refresh a couple of times and try now
