### ISSUE TITLE
Problem with accent mark

### ISSUE THREAD

**Issue by GastonUC** [Miodec/monkey-type#336]
I've been using ur page for a while, i use it on both, mac and pc, but a while ago in my mac doesn't read the accent mark when i do it, but when i write outside of the page, it works, so i don't know what it is. In my pc works fine, there is no problem, but in mac i can't do tests because of that.

**Comment by Miodec** [comment]
What do you mean by the accent mark

**Comment by GastonUC** [comment]
I mean accented characters, in spanish, like é, ó, í, á, etc

**Comment by Miodec** [comment]
It works on windows but not on mac?

**Comment by GastonUC** [comment]
Yup, in windows i don't have any problem, but in mac it doesn't work, and i tried it in different browsers, and it doesn't work at all

**Comment by Miodec** [comment]
Thats weird, because i would expect it to not work at all. Its been an issue since the start of the project. Is it the same combination of key on both machines?

**Comment by GastonUC** [comment]
Yes, it's the same

**Comment by GastonUC** [comment]
I usually use the key that is next to the ';' on mac (bc the keyboard is for EN), and i use the configuration "Español-ISO".
Meanwhile in my main pc, which is windows, i use the key next to the 'ñ' key, because it's a keyboard for spanish, and i also use the configuration "Español (España, internacional)". I hope i have explained myself well and maybe the information helps.

**Comment by Miodec** [comment]
Sorry but currently i dont have a fix for this. Its been an issue since the project started just because of the way I'm handling input.

**Comment by GastonUC** [comment]
Np, just wanted to notice the problem, didn't see the other commets.
