### ISSUE TITLE
Graph Shouldn’t Start at 0

### ISSUE THREAD

**Issue by lumitry** [Miodec/monkey-type#345]
On the profile page, the WPM graph should start at just below the lowest number on the graph, so it’s easier to see the differences between them. For example, if the lowest WPM is 59, the graph should start at 50. Just round down to the lowest 10.

**Comment by Miodec** [comment]
Personally dont agree as it exaggerates the data, and also because of the not static graph range, the scale is not constant - meaning sometimes a big change can mean 50 and sometimes 10.

**Comment by Miodec** [comment]
Added
