### ISSUE TITLE
Accuracy Label on Graph is Confusing

### ISSUE THREAD

**Issue by FatBanana** [Miodec/monkey-type#346]
The graph in the user profile is very confusing. It says accuracy on the right side but none of the points correspond to accuracy.
![image](https://user-images.githubusercontent.com/34758569/92553697-7be58e00-f218-11ea-8416-4f36a72e35bc.png)

**Comment by Miodec** [comment]
I was playing around with displaying accuracy there and forgot to remove it. Fixed.
