### ISSUE TITLE
[feature] Local average WPM on graph?

### ISSUE THREAD

**Issue by winterNebs** [Miodec/monkey-type#348]
It would be interesting to see what your local average wpm, maybe at different scales even.

For example, per word, per 2 words, per 1 second, per 5 seconds, etc

This can show you what words you type well and what words you may struggle with typing, and shows in more detail, where your speed ups and slow downs are.

**Comment by Miodec** [comment]
You can hover over the graph to see which words you were typing at that time

**Comment by winterNebs** [comment]
how is the raw wpm calculated at each word? the info page just says its momentary but what exactly does that mean?
I think it would be interesting to know exactly how fast you typed the word that way you can more easily pinpoint which words you have difficulty typing

**Comment by Miodec** [comment]
Right now we dont track wpm per word, only per second. Thats what i mean by momentary ( that very second )
