### ISSUE TITLE
Need a line for error, not just wpm

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkey-type#354]
Some of keybr's graphs are pretty useful. Any chance/plans monkey-type will absorb some of it? Love the site, please keep up the good work.

**Comment by pingshunhuangalex** [comment]
Sorry, like in the account history bit. We have a line showing how wpm changes across the lifespan and interpolated lines. I'm hoping we can add another line (red) on the same chart showing the error rate/error number across the account lifespan so I can also see if my accuracy is improving.

**Comment by Miodec** [comment]
Why not just add an accuracy line then

**Comment by pingshunhuangalex** [comment]
Oh we can do that already? I didn't notice that. Do you have a screenshot for that? Thanks.

**Comment by Miodec** [comment]
Well, it’s not available yet, but i thought about adding an accuracy line

**Comment by pingshunhuangalex** [comment]
Right, yeah accuracy line does the trick too. Maybe also a consistency line as well

**Comment by Miodec** [comment]
Added
