### ISSUE TITLE
An option to restart tests using <Esc> while using <Tab> for command

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkey-type#355]
I'm quite used to using `Esc` to restart the tests in keybr and also I bind `Esc` to `CapsLock` because of vim. Just wondering by any chance we can add a toggle to swap the current behaviour of `Esc` and `Tab`? Thanks.

**Comment by Miodec** [comment]
Possible - could add it soon

**Comment by Miodec** [comment]
Added
