### ISSUE TITLE
Keybind for repeat same test button 

### ISSUE THREAD

**Issue by Xieyt** [Miodec/monkey-type#363]
Please add a keybind for repeating same test, just like tab to go to new test ,  so that we don't have to take our hands off our keyboard and press the repeat button. 
It will help in improving the accuracy and also help in completing paragraph in master mode.

**Comment by Miodec** [comment]
Tab + enter. Or just tab with quick tab enabled in the settings

**Comment by Miodec** [comment]
Nevermind, you mean repeating the same text

**Comment by userrand** [comment]
I am not sure where this quick tab setting is (unless it is the quick repeat setting but that does note seem to solve the problem) and it is unclear to me why this was closed in the end
