### ISSUE TITLE
Pace caret move out of the paragraph

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkey-type#364]
When I turn pace caret on (at pb), it'll move out of the 3-line paragraph when I type too slow (I'm learning an alternative keymap).

And even worse once it's beyond maybe line 6, it errors out saying invalid test, detected AFK and force the typing to end... (I also have keyboard layout displayed at the bottom of the paragraph, maybe that's why?)

Great concept tho, like racing with a shadow mode. Please keep up the good work. I love this site so much!

**Comment by Miodec** [comment]
So, unfortunately, with the way im doing line scrolling and word generation I'm not sure if I can figure out a way of hiding the pace caret if it moved beyond the third line. The pace caret did go through some major changes lately, so if you encounter any other bugs let me know.
