### ISSUE TITLE
Split alternative keyboard layout to its own group

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkey-type#365]
I'm trying to pick up an alternative keyboard layout, and monkey type has everything at my fingertip.

However atm, my current learning progress is mixed with the qwerty result I had previously. It'll be nice if alternative keyboard can be recognised as a different mode (like time vs word) and only merge together if I choose to turn all options in the filter section.

What's even cooler is to have the new pace caret feature to honour this settings too, so I can know for sure I'm progressing. Right now the shadow caret just disappears quickly out of the screen while I'm still trying to recall where keys are lol.

Please keep up the good work. Everything feels great on this site!

**Comment by Miodec** [comment]
I would recommend just tagging the results and filtering out by the tag.

**Comment by pingshunhuangalex** [comment]
I'm happy to do it, but will the pace caret work in this case, i.e. it'll track my pb just for that tag?

**Comment by Miodec** [comment]
Not at the moment, im gonna try make tags work with pbs soon but its kinda difficult

**Comment by Miodec** [comment]
#366
