### ISSUE TITLE
Filter options not synced

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkey-type#378]
Not sure how filter options are stored atm. It looks like after a refresh, the filters state is maintained, but sometimes when I reopen the browser, the filter options are gone.

Is it synced with the account? If not, is it worth syncing it? Personally, I don't mind it's kept in the local storage, but some degree of caching should be used here IMO. Thanks.

**Comment by Miodec** [comment]
Im not sure, the filters should be saved. Maybe its a specific filter that is messed up, but I need some more data on whats being broken.

**Comment by pingshunhuangalex** [comment]
I may have some idea. It happens when you push a new version of the website (maybe). Everything was saved properly yesterday, but just now when I opened the site, the filters get default to all filters again. In my case it was easy, I just hit `current settings` and things are back to normal. Hope it helps with the debugging.

**Comment by pingshunhuangalex** [comment]
Actually no. Today every time I close all the tabs in the browser and open them up after a while, all filters would be selected. Maybe there's some issue reading/restoring the synced filters?

**Comment by Miodec** [comment]
So the filters dont save if you close your browser?

**Comment by pingshunhuangalex** [comment]
I can't identify the trigger precisely, but the symptom is if I don't go to the site for a while (usually more than 2 hours), and the next time I go in there's a chance all filters will be turned on (default?) when I go to the account page. I'll need to click on the current settings button to get the chart to display what I want. If I just do a refresh immediately after the filter change, I can see they are saved and restored properly, so it's quite hard to reproduce.

**Comment by pingshunhuangalex** [comment]
Not sure if you did anything recently, but I haven't seen this issue coming back in the past 2 days. If you did address it, feel free to close this issue.

BTW the account page seems to load much slower recently, sometimes even loading for seconds if not forever. Could be just my internet tho...

**Comment by Miodec** [comment]
Yeah i did do a slight rewrite of the config loading. So if you run into this again just open another issue I guess.

As for the account page loading slower, not sure what it could be - didn't change anything major in there lately. If it persists let me know
