### ISSUE TITLE
Command/keybind to switch views

### ISSUE THREAD

**Issue by ivanjermakov** [Miodec/monkey-type#386]
Ability to switch between views (type/leaderboards/info/settings/profile) without using a mouse.
It is probably possible with `Tab` through, but with `quick tab mode` it obviously isn't.

**Comment by Miodec** [comment]
Im not exactly sure how to do it without interfering with the default browser shortcuts.

The only kina close functionality is that you can press Tab anywhere with quick tab enabled to jump back to the test page.
