### ISSUE TITLE
custom pace caret command line sometimes doesnt work (but settings page does)

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkey-type#388]

**Comment by alegottu** [comment]
Can I ask how input is handled for the custom settings in the command line? Apologies if that's an obvious answer but I also tested the custom word count function through the command line, which shares the same problem. Replacing the input with a simple prompt fixes each.

**Comment by alegottu** [comment]
That is really weird, maybe its some sort of compatibility issue, like depending on the browser/extensions? I'll look further into it on my system as soon as I can.

**Comment by alegottu** [comment]
Actually never mind, I just figured it out. The error only occurs when you click on the suggestions rather than using the keyboard alone, but I can't exactly figure out how to fix it just by looking at the events. Any ideas?

**Comment by Miodec** [comment]
I think i found what was going on. Should be deployed on to the live website soon.
