### ISSUE TITLE
Command line language change not working

### ISSUE THREAD

**Issue by ivanjermakov** [Miodec/monkey-type#389]
Language change is ignored

**Comment by Miodec** [comment]
Cant reproduce this. Are you sure you are using the random text modes? (time and words) It will not work for quotes as we only have English quotes at the moment, and obviously wont work for custom either

**Comment by ivanjermakov** [comment]
I narrowed the issue down.
In order to reproduce:
 - Set language to English
 - Press `Esc`
 - Enter `Change language`
 - Press `Enter`
 - Select `English 10k` **with `Enter` key** (with mouse click everything works as expected)

Result: language is not changed.
As far as I can tell this happens only within English language group. So selecting e.g. German, instead of English 10k works fine.

**Comment by ivanjermakov** [comment]
Correct. Tried it from incognito mode - everything works as expected.
Might close the issue for now, may reopen when I'll understand why it's happening.
