### ISSUE TITLE
Typography Symbols are not mapped to universal keyboard standards.

### ISSUE THREAD

**Issue by RebonackAl** [Miodec/monkey-type#390]
Common typography type sets, such as:

> “ (\&ldquo; \&#8220;)
> ” (\&rdquo;	\&#8221;)
> ’ (\&lsquo;	\&#8216;)
> ‘ (\&rsquo;	\&#8217;)
>  , (\&sbquo;	\&#8218;)
>  — (\&mdash;  \&#8212;)
>  … (\&hellip; \&#8230;)

remain when entered in custom text. Example: For the opening quote mark “ a user would have to enter Shift+Option+[ instead of the universal quote ".

It is very common for ebooks to have this correct typography.
The use case it breaks is a user wanting to enter in text from an ebook or source that has correct typography, perhaps to practice touch typing or improve speed, whilst also reading something they enjoy.

**Comment by Miodec** [comment]
Merged
