### ISSUE TITLE
Pace Caret doesn't work for the first test after you load up the website (Bug)

### ISSUE THREAD

**Issue by shaunsingh** [Miodec/monkey-type#404]
When you first load up the website, and do a test, then the pace caret doesn't show up. However after re-doing the test, it show's up

Video: (sorry if its a big laggy): https://drive.google.com/file/d/11hC-wh6H5yywiWzz1nrm-QTZ9VsOJ8Ks/view?usp=sharing

As you can see, when I first load up the page and do a test, it doesn't load the caret, but on the second test it does

My system specs are as following: macOS Catalina, safari 14, core 2 duo and a 9400m

**Comment by Miodec** [comment]
This happens when you start the test before your account (including your pb speed) is loaded. No way to fix it as far as I'm aware.
