### ISSUE TITLE
Missing button text

### ISSUE THREAD

**Issue by theamanjs** [Miodec/monkey-type#409]
The `blind mode` option under settings which have two options, either we can select `off` or `on`. The text of `on` button is missing. You can see in the screenshot attached below.
![Screenshot_2020-10-09_08-29-36](https://user-images.githubusercontent.com/38748298/95536839-a0947780-0a09-11eb-945a-cd181fc92454.png)

I've figured out why it is happening and fixed this on my local machine. I think this was missed in this [commit](https://github.com/Miodec/monkey-type/commit/09df26a42c6c184d5c9b7d271f495b7973b4e1f3). I would be glad about fixing this and start my contribution to this project with it :smiley:

**Comment by Miodec** [comment]
Not a bug. Intentional
