### ISSUE TITLE
highlight upcoming nth word to help increase focus on looking ahead

### ISSUE THREAD

**Issue by rolfvreijdenberger** [Miodec/monkey-type#413]
An idea I'd like to pitch would be to highlight the nth word that should be typed.

Increasing your typing speed means you have to read words that are coming up. Making it so that for example the next word or the word after that can be highlighted (text, underline, etc) means your eyes have an easier time tracking and focusing on what is coming up.

**Comment by Miodec** [comment]
There is a read ahead funbox available.
