### ISSUE TITLE
Swap tab and esc not working in practising missed word mode

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkey-type#415]
I was quite excited to see that now the setting will be reverted back to user config after exiting the `practising missed words` mode and it's something that's been bothering me for a while.

However, when I'm trying to generate a new test on the result screen after practising missed words by hitting `Esc` (I have swapping `Esc` and `Tab` setting on in my user config), it just didn't do anything. Just wondering what settings `practising missed words` overrides cuz it should only override type mode related ones IMO.

After going back to the home page with a mouse click (and I saw the `reverting xxx` toast at the top), things seem to be working as expected again. Hope my explanation makes sense. Thanks.

**Comment by Miodec** [comment]
Have `swap tab and esc` enabled
- Complete a test
- Click practise missed words
- Complete that test
- Press esc on the result screen.

Is that not working? I just tried it and it gave me a new test correctly, and showed the `reverting` notification.

**Comment by pingshunhuangalex** [comment]
Mmm, can't reproduce it either today. I'll close the issue for now. Thanks for double-checking.
