### ISSUE TITLE
Words sometimes dont show up when changing into time mode

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkey-type#43]

**Comment by arghblargh** [comment]
When restarting a test or switching to time mode from the results screen, the #words div is set to height: 0px.

**Comment by Miodec** [comment]
Fixed in bf75fc862e76540efea745c1ca59d6923bda7ea1

**Comment by Miodec** [comment]
Actually fixed in 54126a4f96cae8f9d70c3e86ba159cd595883275
