### ISSUE TITLE
Discord integration

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkey-type#54]
Make a discord bot that integrates with the website, assigns the top wpm role automatically and later  on mentions users if they get beaten on the leaderboards

**Comment by Le-SirH** [comment]
Is there/will there be an API for this?

**Comment by Syn-Tax** [comment]
There is a discord.js api for node which should work, I've not used it for a while but I can work on it if no one else is.

**Comment by Miodec** [comment]
There is a big part of it thats already written by a friend, but thats been put on hold. Im going to follow up on it soon.

**Comment by Le-SirH** [comment]
Is there room for volunteers to work on the bot as well?

**Comment by Le-SirH** [comment]
Here's an idea:

In order to get a role in the Discord server, you must link your Discord account to your monkey-type account. That way, we can use the Discord ID to give them a role based on their best test score.

**Comment by 8cy** [comment]
even if the api was private *please no* a discord bot would be a pretty cool project. would love to help with this as i have a good background with discord.js and it's sister framework, commando. as for the account linking process, this could be achieved in a number of ways, a possibility being that a user is able to direct message the bot with a specific command, then, providing a account token or db id as a argument, that being if we aren't able to get the discord account linking integration working.

a pseudo mock of the account linking system could be;

user > mt!link <username>

bot > Please provide your account token

user > account token

bot > cool linked lol

**Comment by Miodec** [comment]
Alright, sorry it took so long. Here it is https://github.com/Miodec/monkey-bot

Just the basics, its my first bot aswell so feel free to suggest changes and features.
