### ISSUE TITLE
Chinese don't quite work

### ISSUE THREAD

**Issue by Lichtspektrum** [Miodec/monkey-type#59]
Chinese don't quite work on macOS with built in input method. In fact all of the few type test websites that feature Chinese don't work. Props for the effort though. Amazing website.

**Comment by Miodec** [comment]
Thanks! Could you check on the dev page instead? Ive got a new input method there: https://dev.monkey-type.com

**Comment by Lichtspektrum** [comment]
> Thanks! Could you check on the dev page instead? Ive got a new input method there: https://dev.monkey-type.com
> 
> Dont mind the visible text box

Yes the Chinese input on the dev page works. Appreciate for your effort! Truly great site with great aesthetics.

**Comment by Miodec** [comment]
Same issue as #36
