### ISSUE TITLE
Add book quotes mode

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkey-type#61]

**Comment by christophersarmiento** [comment]
Started working on. Will likely add a field for users to submit their own quotes for review as well.

**Comment by g-harel** [comment]
This looks like it was implemented in #169, but it doesn't seem like quotes stats are being reported on the profile page.

**Comment by snth** [comment]
Similar to the book quotes mode, it would be great if one could type pieces of code from Github. Similar to what's available on typing.io. This way one could type-read some great code repos while practicing one's typing.

**Comment by g-harel** [comment]
Really like this feature, great work!
