### ISSUE TITLE
Add scrolling when text is exceeding the screen size

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkey-type#67]

**Comment by bhomie** [comment]
Taking a look at this.

**Comment by bhomie** [comment]
Can you clarify what you mean by scrolling? Horizontal, vertical, the window width, the container of the test words?

**Comment by Miodec** [comment]
Vertically.

You can get a long test by using custom modes, and sometimes the words might be overflowing the window (or if your monitor is small). The idea i had was to look at the current active word, and make sure its always visible. Currently you have to scroll manually to see more words.

**Comment by Miodec** [comment]
Now it doesnt seem to scroll anymore. Plus i think that because you set the browser height at the start, if the user changed the size of the browser the scrolling might stop
